In [1]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm

## Cutlet problem

In [2]:
cutlet= pd.read_csv('Cutlets.csv')
cutlet

Unit A  Unit B
0   6.8090  6.7703
1   6.4376  7.5093
2   6.9157  6.7300
3   7.3012  6.7878
4   7.4488  7.1522
5   7.3871  6.8110
6   6.8755  7.2212
7   7.0621  6.6606
8   6.6840  7.2402
9   6.8236  7.0503
10  7.3930  6.8810
11  7.5169  7.4059
12  6.9246  6.7652
13  6.9256  6.0380
14  6.5797  7.1581
15  6.8394  7.0240
16  6.5970  6.6672
17  7.2705  7.4314
18  7.2828  7.3070
19  7.3495  6.7478
20  6.9438  6.8889
21  7.1560  7.4220
22  6.5341  6.5217
23  7.2854  7.1688
24  6.9952  6.7594
25  6.8568  6.9399
26  7.2163  7.0133
27  6.6801  6.9182
28  6.9431  6.3346
29  7.0852  7.5459
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

In [3]:
unitA=pd.Series(cutlet.iloc[:,0]) 

In [4]:
unitA

0     6.8090
1     6.4376
2     6.9157
3     7.3012
4     7.4488
5     7.3871
6     6.8755
7     7.0621
8     6.6840
9     6.8236
10    7.3930
11    7.5169
12    6.9246
13    6.9256
14    6.5797
15    6.8394
16    6.5970
17    7.2705
18    7.2828
19    7.3495
20    6.9438
21    7.1560
22    6.5341
23    7.2854
24    6.9952
25    6.8568
26    7.2163
27    6.6801
28    6.9431
29    7.0852
30    6.7794
31    7.2783
32    7.1561
33    7.3943
34    6.9405
Name: Unit A, dtype: float64

In [5]:
unitB=pd.Series(cutlet.iloc[:,1])
unitB

0     6.7703
1     7.5093
2     6.7300
3     6.7878
4     7.1522
5     6.8110
6     7.2212
7     6.6606
8     7.2402
9     7.0503
10    6.8810
11    7.4059
12    6.7652
13    6.0380
14    7.1581
15    7.0240
16    6.6672
17    7.4314
18    7.3070
19    6.7478
20    6.8889
21    7.4220
22    6.5217
23    7.1688
24    6.7594
25    6.9399
26    7.0133
27    6.9182
28    6.3346
29    7.5459
30    7.0992
31    7.1180
32    6.6965
33    6.5780
34    7.3875
Name: Unit B, dtype: float64

In [6]:
p_value=stats.ttest_ind(unitA,unitB)         
p_value

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [7]:
p_value[1]

0.4722394724599501

## pvalue > 0.05, hence null hypothesis is not rejected

## Customer order form

In [8]:
from scipy.stats import chi2_contingency

In [9]:
customer = pd.read_csv('Costomer+OrderForm.csv')
customer

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [10]:
customer.dtypes

Phillippines    object
Indonesia       object
Malta           object
India           object
dtype: object

In [11]:
customer.describe()

Phillippines   Indonesia       Malta       India
count           300         300         300         300
unique            2           2           2           2
top      Error Free  Error Free  Error Free  Error Free
freq            271         267         269         280

In [14]:
Indo_Phill = pd.crosstab(customer.Phillippines,customer.Indonesia)
Indo_Phill

Indonesia     Defective  Error Free
Phillippines                       
Defective             2          27
Error Free           31         240

In [20]:
chi_value, pval, df, expected_value = stats.chi2_contingency(Indo_Phill)
chi_value, pval, df, expected_value

(0.1856391005881107,
 0.6665712150680798,
 1,
 array([[  3.19,  25.81],
        [ 29.81, 241.19]]))

In [21]:
pval = 0.6665712150680798

In [22]:
if pval<=0.05:
    print("We reject the null hypothesis saying that there is a signifcant difference.")
else:
    print("We do not reject the null hypothesis saying that there is no signifcant difference.")

We do not reject the null hypothesis saying that there is no signifcant difference.


In [24]:
Ind_Malta = pd.crosstab(customer.India,customer.Malta)
Ind_Malta

Malta       Defective  Error Free
India                            
Defective           0          20
Error Free         31         249

In [25]:
chi_value, pval, df, expected_value = stats.chi2_contingency(Ind_Malta)
chi_value, pval, df, expected_value

(1.419106436194816,
 0.23355053527979247,
 1,
 array([[  2.06666667,  17.93333333],
        [ 28.93333333, 251.06666667]]))

In [26]:
pval = 0.23355053527979247

In [27]:
if pval<=0.05:
    print("We reject the null hypothesis saying that there is a signifcant difference.")
else:
    print("We do not reject the null hypothesis saying that there is no signifcant difference.")

We do not reject the null hypothesis saying that there is no signifcant difference.


## LabTAT Data

In [29]:
lab_data =  pd.read_csv('LabTAT.csv')
lab_data.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [30]:
lab_data.dtypes

Laboratory 1    float64
Laboratory 2    float64
Laboratory 3    float64
Laboratory 4    float64
dtype: object

In [38]:
Lab_data1=pd.Series(lab_data.iloc[:,0])
Lab1

0      185.35
1      170.49
2      192.77
3      177.33
4      193.41
        ...  
115    178.49
116    176.08
117    202.48
118    182.40
119    182.09
Name: Laboratory 1, Length: 120, dtype: float64

In [39]:
Lab_data2=pd.Series(lab_data.iloc[:,1])
Lab2

0      165.53
1      185.91
2      194.92
3      183.00
4      169.57
        ...  
115    170.66
116    183.98
117    174.54
118    197.18
119    215.17
Name: Laboratory 2, Length: 120, dtype: float64

In [40]:
Lab_data3=pd.Series(lab_data.iloc[:,2])
Lab3

0      176.70
1      198.45
2      201.23
3      199.61
4      204.63
        ...  
115    193.80
116    215.25
117    203.99
118    194.52
119    221.49
Name: Laboratory 3, Length: 120, dtype: float64

In [41]:
Lab_data4=pd.Series(lab_data.iloc[:,3])
Lab4

0      166.13
1      160.79
2      185.18
3      176.42
4      152.60
        ...  
115    172.68
116    177.64
117    170.27
118    150.87
119    162.21
Name: Laboratory 4, Length: 120, dtype: float64

### Assumption
### Ho : There is no any significance difference in the average TAT report of the laboratries
### Ha : There is significance difference in the average TAT report of the laboratries

In [35]:
from scipy.stats import f_oneway

In [42]:
t_score,p_value = f_oneway(Lab_data1,Lab_data2,Lab_data3,Lab_data4)
p_value

2.1156708949992414e-57

In [43]:
if p_value<=0.05:
    print("We reject the null hypothesis saying that there is a signifcant difference in the average TAT report of the laboratries.")
else:
    print("We do not reject the null hypothesis saying that there is no signifcant differencen in the average TAT report of the laboratries.")

We reject the null hypothesis saying that there is a signifcant difference in the average TAT report of the laboratries.


## Buyers ratio data

In [44]:
buyer_data = pd.read_csv('BuyerRatio (1).csv')
buyer_data

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [45]:
buyer_data.describe()

East         West        North       South
count    2.000000     2.000000     2.000000    2.000000
mean   242.500000   832.500000   743.500000  410.000000
std    272.236111   976.514465   866.205807  480.832611
min     50.000000   142.000000   131.000000   70.000000
25%    146.250000   487.250000   437.250000  240.000000
50%    242.500000   832.500000   743.500000  410.000000
75%    338.750000  1177.750000  1049.750000  580.000000
max    435.000000  1523.000000  1356.000000  750.000000

In [46]:
del buyer_data['Observed Values']

In [47]:
buyer_data

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

## Ho : All proportions are equal
## Ha : Not all proportions are equal

In [48]:
chi_value, pval, df, expected_value = stats.chi2_contingency(buyer_data)
chi_value, pval, df, expected_value

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [49]:
pval = 0.66

In [50]:
if pval<=0.05:
    print("We reject the null hypothesis saying that not all proportions are equal.")
else:
    print("We do not reject the null hypothesis saying that  all proportions are equal.")

We do not reject the null hypothesis saying that  all proportions are equal.


## ----------------------------------------------------------------------------------------------------------------------------------