 ## y -> Whether the client has subscribed a term deposit or not 

In [7]:
import pandas as pd
import numpy as np

In [3]:
bank_data =  pd.read_csv('bank-full.csv', sep = ';')
bank_data.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

In [14]:
bank_data.shape

(45211, 17)

In [6]:
bank_data.isna().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [11]:
bank_data['y'].value_counts()

no     39922
yes     5289
Name: y, dtype: int64

In [13]:
bank_data['pdays'].value_counts()

-1      36954
 182      167
 92       147
 91       126
 183      126
        ...  
 465        1
 529        1
 18         1
 434        1
 831        1
Name: pdays, Length: 559, dtype: int64

In [15]:
bank_data['job'].astype("category").value_counts()

blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: job, dtype: int64

In [16]:
bank_data['marital'].astype("category").value_counts()

married     27214
single      12790
divorced     5207
Name: marital, dtype: int64

In [17]:
bank_data['education'].astype("category").value_counts()

secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: education, dtype: int64

In [18]:
bank_data['contact'].astype("category").value_counts()

cellular     29285
unknown      13020
telephone     2906
Name: contact, dtype: int64

In [19]:
bank_data['month'].astype("category").value_counts()

may    13766
jul     6895
aug     6247
jun     5341
nov     3970
apr     2932
feb     2649
jan     1403
oct      738
sep      579
mar      477
dec      214
Name: month, dtype: int64

In [20]:
bank_data['poutcome'].astype("category").value_counts()

unknown    36959
failure     4901
other       1840
success     1511
Name: poutcome, dtype: int64

In [21]:
bank_data['default'].astype("category").value_counts()

no     44396
yes      815
Name: default, dtype: int64

In [4]:
# Applying one hot encoding
bank_data2=pd.get_dummies(bank_data,columns=['job','marital','education','contact','poutcome','month'])
bank_data2

age default  balance housing loan  day  duration  campaign  pdays  \
0       58      no     2143     yes   no    5       261         1     -1   
1       44      no       29     yes   no    5       151         1     -1   
2       33      no        2     yes  yes    5        76         1     -1   
3       47      no     1506     yes   no    5        92         1     -1   
4       33      no        1      no   no    5       198         1     -1   
...    ...     ...      ...     ...  ...  ...       ...       ...    ...   
45206   51      no      825      no   no   17       977         3     -1   
45207   71      no     1729      no   no   17       456         2     -1   
45208   72      no     5715      no   no   17      1127         5    184   
45209   57      no      668      no   no   17       508         4     -1   
45210   37      no     2971      no   no   17       361         2    188   

       previous  ... month_dec  month_feb  month_jan  month_jul  month_jun  \
0             0  ...         0          0          0          0          0   
1             0  ...         0          0          0          0          0   
2             0  ...         0          0          0          0          0   
3             0  ...         0          0          0          0          0   
4             0  ...         0          0          0          0          0   
...         ...  ...       ...        ...        ...        ...        ...   
45206         0  ...         0          0          0          0          0   
45207         0  ...         0          0          0          0          0   
45208         3  ...         0          0          0          0          0   
45209         0  ...         0          0          0          0          0   
45210        11  ...         0          0          0          0          0   

       month_mar  month_may  month_nov  month_oct  month_sep  
0              0          1          0          0          0  
1              0          1          0          0          0  
2              0          1          0          0          0  
3              0          1          0          0          0  
4              0          1          0          0          0  
...          ...        ...        ...        ...        ...  
45206          0          0          1          0          0  
45207          0          0          1          0          0  
45208          0          0          1          0          0  
45209          0          0          1          0          0  
45210          0          0          1          0          0  

[45211 rows x 49 columns]

In [5]:
bank_data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 49 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   age                  45211 non-null  int64 
 1   default              45211 non-null  object
 2   balance              45211 non-null  int64 
 3   housing              45211 non-null  object
 4   loan                 45211 non-null  object
 5   day                  45211 non-null  int64 
 6   duration             45211 non-null  int64 
 7   campaign             45211 non-null  int64 
 8   pdays                45211 non-null  int64 
 9   previous             45211 non-null  int64 
 10  y                    45211 non-null  object
 11  job_admin.           45211 non-null  uint8 
 12  job_blue-collar      45211 non-null  uint8 
 13  job_entrepreneur     45211 non-null  uint8 
 14  job_housemaid        45211 non-null  uint8 
 15  job_management       45211 non-null  uint8 
 16  job_

In [15]:
bank_data2.default.map(dict(yes=1, no=0))
bank_data2.housing.map(dict(yes=1, no=0))
bank_data2.loan.map(dict(yes=1, no=0))
bank_data2.y.map(dict(yes=1, no=0))


bank_data2

age  default  balance  housing  loan  day  duration  campaign  pdays  \
0       58        0     2143        1     0    5       261         1     -1   
1       44        0       29        1     0    5       151         1     -1   
2       33        0        2        1     1    5        76         1     -1   
3       47        0     1506        1     0    5        92         1     -1   
4       33        0        1        0     0    5       198         1     -1   
...    ...      ...      ...      ...   ...  ...       ...       ...    ...   
45206   51        0      825        0     0   17       977         3     -1   
45207   71        0     1729        0     0   17       456         2     -1   
45208   72        0     5715        0     0   17      1127         5    184   
45209   57        0      668        0     0   17       508         4     -1   
45210   37        0     2971        0     0   17       361         2    188   

       previous  ...  month_dec  month_feb  month_jan  month_jul  month_jun  \
0             0  ...          0          0          0          0          0   
1             0  ...          0          0          0          0          0   
2             0  ...          0          0          0          0          0   
3             0  ...          0          0          0          0          0   
4             0  ...          0          0          0          0          0   
...         ...  ...        ...        ...        ...        ...        ...   
45206         0  ...          0          0          0          0          0   
45207         0  ...          0          0          0          0          0   
45208         3  ...          0          0          0          0          0   
45209         0  ...          0          0          0          0          0   
45210        11  ...          0          0          0          0          0   

       month_mar  month_may  month_nov  month_oct  month_sep  
0              0          1          0          0          0  
1              0          1          0          0          0  
2              0          1          0          0          0  
3              0          1          0          0          0  
4              0          1          0          0          0  
...          ...        ...        ...        ...        ...  
45206          0          0          1          0          0  
45207          0          0          1          0          0  
45208          0          0          1          0          0  
45209          0          0          1          0          0  
45210          0          0          1          0          0  

[45211 rows x 49 columns]

## Model building

In [16]:
X = bank_data2.drop(labels = 'y',axis =1)
y = bank_data2[['y']]

In [17]:
X

age  default  balance  housing  loan  day  duration  campaign  pdays  \
0       58        0     2143        1     0    5       261         1     -1   
1       44        0       29        1     0    5       151         1     -1   
2       33        0        2        1     1    5        76         1     -1   
3       47        0     1506        1     0    5        92         1     -1   
4       33        0        1        0     0    5       198         1     -1   
...    ...      ...      ...      ...   ...  ...       ...       ...    ...   
45206   51        0      825        0     0   17       977         3     -1   
45207   71        0     1729        0     0   17       456         2     -1   
45208   72        0     5715        0     0   17      1127         5    184   
45209   57        0      668        0     0   17       508         4     -1   
45210   37        0     2971        0     0   17       361         2    188   

       previous  ...  month_dec  month_feb  month_jan  month_jul  month_jun  \
0             0  ...          0          0          0          0          0   
1             0  ...          0          0          0          0          0   
2             0  ...          0          0          0          0          0   
3             0  ...          0          0          0          0          0   
4             0  ...          0          0          0          0          0   
...         ...  ...        ...        ...        ...        ...        ...   
45206         0  ...          0          0          0          0          0   
45207         0  ...          0          0          0          0          0   
45208         3  ...          0          0          0          0          0   
45209         0  ...          0          0          0          0          0   
45210        11  ...          0          0          0          0          0   

       month_mar  month_may  month_nov  month_oct  month_sep  
0              0          1          0          0          0  
1              0          1          0          0          0  
2              0          1          0          0          0  
3              0          1          0          0          0  
4              0          1          0          0          0  
...          ...        ...        ...        ...        ...  
45206          0          0          1          0          0  
45207          0          0          1          0          0  
45208          0          0          1          0          0  
45209          0          0          1          0          0  
45210          0          0          1          0          0  

[45211 rows x 48 columns]

In [18]:
y

y
0      0
1      0
2      0
3      0
4      0
...   ..
45206  1
45207  1
45208  1
45209  0
45210  0

[45211 rows x 1 columns]

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=0)

In [20]:
X_train.shape,y_train.shape

((36168, 48), (36168, 1))

In [21]:
X_test.shape,y_test.shape

((9043, 48), (9043, 1))

## Model Training

In [22]:
import warnings
warnings.filterwarnings('ignore')

In [23]:
from sklearn.linear_model import LogisticRegression

In [34]:
logistic_model = LogisticRegression()
logistic_model.fit(X_train,y_train)

LogisticRegression()

## Model Testing

In [35]:
y_pred_train = logistic_model.predict(X_train)
y_pred_train

array([1, 0, 0, ..., 0, 0, 0])

In [26]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [27]:
accuracy_score(y_train,y_pred_train)

0.8920869276708693

In [29]:
confusion_matrix(y_train,y_pred_train)

array([[31331,   611],
       [ 3292,   934]], dtype=int64)

## Test data

In [36]:
y_test_pred = logistic_model.predict(X_test)
y_test_pred

array([0, 1, 0, ..., 0, 0, 0])

In [37]:
accuracy_score(y_test,y_test_pred)

0.8877584872276899

In [39]:
confusion_matrix(y_test,y_test_pred)

array([[7823,  157],
       [ 858,  205]], dtype=int64)

In [40]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       0.90      0.98      0.94      7980
           1       0.57      0.19      0.29      1063

    accuracy                           0.89      9043
   macro avg       0.73      0.59      0.61      9043
weighted avg       0.86      0.89      0.86      9043

